- name: set tmp file name
  set_fact:
          tmp_file: "/tmp/passwords-{{ ansible_date_time.iso8601 }}"
  run_once: true

- name: check if tempfile exists
  stat:
    path: "{{ tmp_file }}"
  register: stat_result
  delegate_to: 127.0.0.1

- name: create tmpfile
  file:
    path: "{{ tmp_file }}"
    state: touch
    mode: 0600
  delegate_to: 127.0.0.1
  when: not stat_result.stat.exists

- name: add line in file
  lineinfile:
    path: "{{ tmp_file }}"
    line: url,username,password,extra,name,group,fav
    mode: 0600
  delegate_to: 127.0.0.1
  when: not stat_result.stat.exists

- name: create password and add to csv
  lineinfile:
    path: "{{ tmp_file }}"
    line: "{{ inventory_hostname }},{{ username }},{{ my_pass }},,,backend,0"
    mode: 0600
  delegate_to: 127.0.0.1
  when: not stat_result.stat.exists
