- name: import data from "{{ tmp_file }}"
  read_csv:
    path: "{{ tmp_file }}"
    key: url
  delegate_to: 127.0.0.1
  run_once: true
  register: chostst

- name: add user
  user:
    name: "{{ chostst.dict[inventory_hostname]['username'] }}"
    password: "{{ chostst.dict[inventory_hostname]['password']|password_hash('sha512') }}"
    create_home: true
    groups: "{{ sudo_group }}"
    append: true
    generate_ssh_key: true

- name: give output to sterr
  debug:
    msg: "host: {{ inventory_hostname }} user: {{ chostst.dict[inventory_hostname]['username'] }} password: {{ chostst.dict[inventory_hostname]['password'] }}"

- name: copy ssh keys
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
