- name: install epel
  yum:
          name: epel-release
          state: present
  when: ansible_distribution == "CentOS"
- name: update CentOS system
  yum:
          name: 'python-setuptools, sudo, git, python3-pip, fish, zsh, openssh, sudo'
          state: present
- name: update
  yum:
          name: "*"
          state: latest # noqa 403
- name: install powerline-shell
  pip:
          name: powerline-shell
          state: present
          executable: pip3
