- name: Update all packages to their latest version
  apt:
          update_cache: true
          name: "*"
          state: latest # noqa 403

- name: install specific packages
  apt:
          name: 'sudo,git,python3-pip,fish,zsh,ssh,sudo'
          state: present

- name: install powerline-shell
  pip:
          name: powerline-shell
          state: present
